
= ECX Client

This project aims to build a Python client for Catalogic Software's 
https://catalogicsoftware.com/products/ecx/[ECX] product. 

This repo holds two components. 

- An SDK that can be used by anyone interested in integrating ECX
  operations in their workflow.

- A command line utility with which ECX operations can be performed.

== Usage

....
$ git clone --recursive https://github.com/catalogicsoftware/ecxclient.git

$ cd ecxclient/scripts
$ ./ecx --help

Usage: ecx [OPTIONS] COMMAND [ARGS]...

  ecx is a command line tool with which ECX operations can be carried out.

Options:                                                                                                                                       --url URL          ECX url.
  --user USERNAME    ECX user.
  --passwd PASSWORD  ECX password.
  -v, --verbose      Enables verbose mode.
  --version          Show the version and exit.
  --help             Show this message and exit.

Commands:
  identity  Identity resource.
  user      User resource.

# This connects to ECX on localhost.
$ ./ecx --user admin --passwd <PASSWORD> user list

# To connect to a different host
$ ./ecx --url https://1.2.3.4:8443 --user admin --passwd <PASSWORD> user list
....
