#!/usr/bin/env python
#-*- mode: Python;-*-

import ConfigParser
import json
import logging
import os
import sys
import tempfile
import traceback

script_dir = os.path.dirname(os.path.abspath(sys.argv[0]))
root_dir = os.path.abspath(os.path.join(script_dir, ".."))
dependencies_dir = os.path.join(root_dir, "dependencies")

sys.path.insert(0, root_dir)
sys.path.insert(0, os.path.join(dependencies_dir, "click"))
sys.path.insert(0, os.path.join(dependencies_dir, "requests"))

import click
import requests
from requests.auth import HTTPBasicAuth
from requests.exceptions import HTTPError

from src import client
from src.client import pass_context
from src import util

cmd_folder = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'commands'))

class MyCLI(click.MultiCommand):
    def list_commands(self, ctx):
        rv = []
        for filename in os.listdir(cmd_folder):
            if filename.endswith('.py') and filename.startswith('cmd_'):
                rv.append(filename[4:-3])
        rv.sort()
        return rv

    def get_command(self, ctx, name):
        try:
            if sys.version_info[0] == 2:
                name = name.encode('ascii', 'replace')

            mod = __import__('commands.cmd_' + name, None, None, ['cli'])
        except ImportError:
            traceback.print_exc()
            return

        return mod.cli


@click.command(cls=MyCLI)
@click.option('--url', envvar='ECX_URL', default='http://localhost:8082', metavar='URL', help='ECX url.')
@click.option('--user', envvar='ECX_USER', default='admin', metavar='USERNAME', help='ECX user.')
@click.option('--passwd', envvar='ECX_PASSWD', default=None, metavar='PASSWORD', help='ECX password.')
@click.version_option('1.0')
@pass_context
def cli(ctx, url, user, passwd):
    """ecx is a command line tool with which ECX operations
    can be carried out.
    """

    ctx.ecx_session = client.EcxSession(url, user, passwd)

# cli = MyCLI(help='Script to perform ECX operations. ')

def init_logging():
    fd, logfile = tempfile.mkstemp(suffix='.txt', prefix='ecxclient')
    os.close(fd)
    logging.basicConfig(filename=logfile, level=logging.DEBUG, format='%(asctime)-15s: %(levelname)s: %(message)s')

if __name__ == '__main__':
    init_logging()

    try:
        cli()
    except Exception as e:
        logging.error(traceback.format_exc())
        click.secho(str(e), fg='red')
        if isinstance(e, HTTPError) and e.response.content:
            logging.error(e.response.content)
            d = json.loads(e.response.content)
            click.secho('%s (%s)' % (d.get('id', 'Unknown'), d.get('description', 'Unknown')), fg='red')

        sys.exit(1)
